apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "crd-manager.fullname" . }}
  labels:
    {{- include "crd-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "2"
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "crd-manager.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "crd-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
