apiVersion: v2
name: crd-manager
description: A Helm chart for AppsCode SaaS Calalog
type: application
version: v2026.1.15
appVersion: v0.1.0
home: https://github.com/appscode-cloud/crd-manager
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
  - https://github.com/appscode-cloud/crd-manager
maintainers:
  - name: appscode
    email: support@appscode.com
